server:
  port: 8087

spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=employee_schema
    username: postgres
    password: 54321

  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml

