spring:
  profiles:
    active: dev


server:
  port: 8087

---

spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=employee_schema
    username: myuser
    password: 123
